name: Check Version

on:
  pull_request:
    branches: [ "release" ]
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Check for tag
      run: |
        file_path="src-tauri/ccv/tauri.conf.json";
        if [ ! -f ${file_path} ]; then
          echo "${file_path} not found!";
          exit 1;
        fi
        version=$(jq src-tauri/ccv/tauri.conf.json .version)
        if [ -z "$(git tag -l "${version}")" ]; then
          echo "${version} already exists. Please update version"
          exit 1;
        fi
  
