name: Check Version

on:
  pull_request:
    branches: [ "release", "main" ]

jobs:
  build:
    name: check-version

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Check for existing release
      run: |
        CONFIG_FILE_PATH="src-tauri/ccv/tauri.conf.json";
        if [ ! -f ${CONFIG_FILE_PATH} ]; then
            echo "${CONFIG_FILE_PATH} not found!";
            exit 1;
        fi
        VERSION="ccv-v$(jq -r .version ${CONFIG_FILE_PATH})"
        if [ -n "$(git tag -l "${VERSION}")" ]; then
            echo "${VERSION} already exists. Please update version"
            exit 1;
        fi
    - name: Check for change log
      run: |
        CONFIG_FILE_PATH="src-tauri/ccv/tauri.conf.json";
        VERSION="$(jq -r .version ${CONFIG_FILE_PATH})"
        CHANGE_LOG_FILE_PATH="./change-log.json";
        if [ -n "$(jq -r .${VERSION} ${CHANGE_LOG_FILE_PATH})" ]; then
            echo "Change log for version ${VERSION} is not defined"
            exit 1;
        fi
        CHANGE_LOG=$(jq -r '.${VERSION} | join("\n")' ${CHANGE_LOG_FILE_PATH});
        echo CHANGE_LOG;
  
