name: My checs

on: workflow_dispatch 

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: calculating sha for macOS ARM
        if: matrix.args == '--target aarch64-apple-darwin'
        run: |
          VERSION=$(jq -r '.version' ./src-tauri/ccv/tauri.conf.json)
          ARTIFACT_PATH=${GITHUB_WORKSPACE}/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/ccv_${VERSION}_aarch64.dmg
          echo "shasum version $(shasum --version)"
          echo "ARTIFACT_PATH ${ARTIFACT_PATH}"
          
      - name: calculating sha for macOS Intel
        if: matrix.args == '--target x86_64-apple-darwin'
        run: |
          VERSION=$(jq -r '.version' ./src-tauri/ccv/tauri.conf.json)
          ARTIFACT_PATH=${GITHUB_WORKSPACE}/src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/ccv_${VERSION}_x64.dmg
          echo "shasum version $(shasum --version)"
          echo "ARTIFACT_PATH ${ARTIFACT_PATH}"
