name: Test

on:
  pull_request:
    branches: [ "main", "release" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
    - name: Build
      working-directory: src-tauri
      run: cargo build --verbose
    - name: Run test
      working-directory: src-tauri
      run: cargo test --verbose
